Feature/43538 data sync user input
DFEAGILEDEVOPS/MTC pull request #1737
Opened 2020-10-28 19:32 UTC by jon-shipley

# Draft

Persist user inputs from the SPA into SQL Server

As a part of this PR, the inputs stored in the SPA have been simplified by using the PointerEvents API.

2020-10-29 09:39 UTC, GuyHarwood reviewed
LGSF

2020-11-11 15:56 UTC, GuyHarwood requested changes
LGTM, just the data migrations that need attention.

2020-11-11 15:56 UTC, GuyHarwood commented on tslib/src/functions-throttled/sync-results-to-sql/question.service.spec.ts
> +    jest.spyOn((sut as any), 'sqlGetQuestionData').mockReturnValue(Promise.resolve([mockQuestion, mockWarmupQuestion]))
interesting way to mock the injected sql service!

2020-11-11 16:37 UTC, jon-shipley commented on db/migrations/schema-objects/20201030104251.do.add-pen-input-type.sql
> +INSERT INTO mtc_results.userInputTypeLookup (code, name) VALUES ('P', 'Pen');
Done!  However, the order was as expected.

2020-11-11 16:43 UTC, GuyHarwood approved these changes
Thanks for the changes

2020-11-26 14:42 UTC, merged